# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b1de989556bb0094694af50a0995de035636a178f5b8acb4e28ebd4a35ab473d21c0c8182d77282090d117b400d5ca323561d7eeb54baccc693a5f64468695a

test:
  secret_key_base: 50c3d8e43c33ff26c6838b72b05eeb01ea1880d14a84f555e38c70bca0df50bd110f8ba895f5888f22de9dbf57811e454498658ee2a6e4c81cf3355c9f89f2ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
